name: masked_text_input_formatter
description: Package that provides text formatting for TextField and TextFormField.
version: 0.0.1
author: Sebastian Arriola
homepage: www.github.com/sebdeveloper6952/MaskedTextInputFormatter

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
